package ro.nectariepopa.crediblecrowd.velocity;

import com.google.inject.Inject; import com.velocitypowered.api.command.*; import com.velocitypowered.api.event.Subscribe; import com.velocitypowered.api.event.connection.*; import com.velocitypowered.api.event.player.ServerPostConnectEvent; import com.velocitypowered.api.event.proxy.*; import com.velocitypowered.api.plugin.Plugin; import com.velocitypowered.api.plugin.annotation.DataDirectory; import com.velocitypowered.api.proxy.*; import com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier; import com.velocitypowered.api.proxy.server.*; import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.*; import java.util.*; import java.util.concurrent.TimeUnit; import net.kyori.adventure.text.Component; import net.kyori.adventure.text.event.*; import net.kyori.adventure.text.format.NamedTextColor; import org.slf4j.Logger; import ro.nectariepopa.crediblecrowd.core.*;

@Plugin(id="crediblecrowd",name="CredibleCrowd",version="1.4.4",description="Consistent configurable virtual population for Velocity",authors={"nectariepopa20"},url="https://github.com/nectariepopa20/CredibleCrowd")
public final class CredibleCrowdVelocity {
 private static final MinecraftChannelIdentifier SYNC=MinecraftChannelIdentifier.create("crediblecrowd","sync"); private final ProxyServer proxy; private final Logger log; private final Path dir; private final MojangNameResolver nameResolver=new MojangNameResolver(); private final UUID syncSession=UUID.randomUUID(); private final Map<String,List<VirtualPlayerIdentity>> lastSentByServer=new HashMap<>(); private volatile VelocitySettings settings; private volatile Messages messages; private volatile CrowdSimulator simulator; private volatile List<String> names=List.of(); private volatile CrowdSnapshot snapshot=new CrowdSnapshot(Instant.EPOCH,0,List.of(),Map.of()); private volatile int lastBroadcastTotal=-1; private volatile long lastAdvanceEpoch; private long syncRevision;
 @Inject public CredibleCrowdVelocity(ProxyServer proxy,Logger log,@DataDirectory Path dir){this.proxy=proxy;this.log=log;this.dir=dir;}
 @Subscribe public void onStart(ProxyInitializeEvent event){try{copyDefault("config.yml");copyDefault("names.txt");copyDefault("messages.yml");reload();}catch(Exception e){throw new IllegalStateException("Cannot load CredibleCrowd",e);}proxy.getChannelRegistrar().register(SYNC);registerCommands();proxy.getScheduler().buildTask(this,this::scheduledRefresh).repeat(1,TimeUnit.SECONDS).schedule();refresh();log.info("CredibleCrowd enabled with {} candidate names",names.size());}
 private void registerCommands(){CommandManager manager=proxy.getCommandManager();for(String alias:List.of("server","glist","find","ping"))if(manager.hasCommand(alias))manager.unregister(alias);manager.register(manager.metaBuilder("server").plugin(this).build(),new ServerCommand());manager.register(manager.metaBuilder("glist").aliases("ccplayers").plugin(this).build(),new GlistCommand());manager.register(manager.metaBuilder("find").plugin(this).build(),new FindCommand());manager.register(manager.metaBuilder("ping").plugin(this).build(),new PingCommand());manager.register(manager.metaBuilder("crediblecrowd").aliases("ccrowd").plugin(this).build(),new AdminCommand());}
 private void scheduledRefresh(){long now=Instant.now().getEpochSecond();if(now-lastAdvanceEpoch>=settings.crowd().activityTickSeconds())refresh();}
 private synchronized void refresh(){Instant now=Instant.now();lastAdvanceEpoch=now.getEpochSecond();Set<String> real=new HashSet<>();proxy.getAllPlayers().forEach(p->real.add(p.getUsername()));CrowdSnapshot previous=snapshot;snapshot=simulator.advance(now,names,real);int displayed=total();if(!snapshot.fakeNames().equals(previous.fakeNames())||!snapshot.byServer().equals(previous.byServer())||displayed!=lastBroadcastTotal){lastBroadcastTotal=displayed;broadcast();}}
 private synchronized void broadcast(){long revision=++syncRevision;LinkedHashMap<String,Integer> counts=new LinkedHashMap<>();for(var registered:proxy.getAllServers()){String name=registered.getServerInfo().getName();counts.put(name,realOn(name)+snapshot.byServer().getOrDefault(name,List.of()).size());}for(var server:proxy.getAllServers()){String localName=server.getServerInfo().getName();List<VirtualPlayerIdentity> current=snapshot.byServer().getOrDefault(localName,List.of()).stream().map(VirtualPlayerIdentity::named).toList();List<VirtualPlayerIdentity> previous=lastSentByServer.getOrDefault(localName,List.of());Set<UUID> currentIds=current.stream().map(VirtualPlayerIdentity::id).collect(java.util.stream.Collectors.toSet());Set<UUID> previousIds=previous.stream().map(VirtualPlayerIdentity::id).collect(java.util.stream.Collectors.toSet());List<VirtualPlayerIdentity> joined=current.stream().filter(identity->!previousIds.contains(identity.id())).toList();List<VirtualPlayerIdentity> departed=previous.stream().filter(identity->!currentIds.contains(identity.id())).toList();try(var bytes=new ByteArrayOutputStream();var out=new DataOutputStream(bytes)){out.writeInt(4);out.writeInt(total());out.writeUTF(localName);out.writeInt(counts.size());for(var entry:counts.entrySet()){out.writeUTF(entry.getKey());out.writeInt(entry.getValue());}out.writeInt(current.size());for(var identity:current)out.writeUTF(identity.name());out.writeLong(syncSession.getMostSignificantBits());out.writeLong(syncSession.getLeastSignificantBits());out.writeLong(revision);writeIdentities(out,current);writeIdentities(out,joined);writeIdentities(out,departed);if(server.sendPluginMessage(SYNC,bytes.toByteArray()))lastSentByServer.put(localName,current);}catch(IOException e){log.warn("Could not encode sync payload",e);}}}
 private static void writeIdentities(DataOutputStream out,List<VirtualPlayerIdentity> identities)throws IOException{out.writeInt(identities.size());for(var identity:identities){out.writeLong(identity.id().getMostSignificantBits());out.writeLong(identity.id().getLeastSignificantBits());out.writeUTF(identity.name());}}
 private void reload() throws IOException {settings=SettingsLoader.load(dir.resolve("config.yml"));messages=Messages.load(dir.resolve("messages.yml"));try(var lines=Files.lines(dir.resolve("names.txt"),StandardCharsets.UTF_8)){names=lines.map(String::trim).filter(s->!s.isBlank()&&!s.startsWith("#")).toList();}simulator=new CrowdSimulator(settings.crowd());lastBroadcastTotal=-1;refresh();}
 private void copyDefault(String name)throws IOException{Files.createDirectories(dir);Path target=dir.resolve(name);if(Files.notExists(target))try(InputStream in=getClass().getClassLoader().getResourceAsStream(name)){if(in==null)throw new FileNotFoundException(name);Files.copy(in,target);}}
 @Subscribe public void onPing(ProxyPingEvent event){ServerPing original=event.getPing();int real=proxy.getPlayerCount(), shown=settings.addToReal()?real+snapshot.fakeCount():snapshot.fakeCount();event.setPing(original.asBuilder().onlinePlayers(shown).maximumPlayers(Math.max(settings.maximumPlayers(),shown)).build());}
 @Subscribe public void onLogin(LoginEvent event){if(settings.reserveNames()&&snapshot.fakeNames().stream().anyMatch(n->n.equalsIgnoreCase(event.getPlayer().getUsername())))event.setResult(LoginEvent.ComponentResult.denied(Component.text(settings.deniedMessage())));}
 @Subscribe public void onServerPostConnect(ServerPostConnectEvent event){broadcast();}
 @Subscribe public void onDisconnect(DisconnectEvent event){broadcast();}
 private int total(){return settings.addToReal()?proxy.getPlayerCount()+snapshot.fakeCount():snapshot.fakeCount();}
 private final class ServerCommand implements SimpleCommand {public void execute(Invocation i){if(!(i.source() instanceof Player player)){i.source().sendMessage(messages.get("players-only"));return;}if(i.arguments().length>0){String requested=i.arguments()[0];Optional<RegisteredServer> target=proxy.getAllServers().stream().filter(s->s.getServerInfo().getName().equalsIgnoreCase(requested)).findFirst();if(target.isEmpty()){player.sendMessage(messages.get("server-not-found","server",requested));return;}player.sendMessage(messages.get("server-connecting","server",target.get().getServerInfo().getName()));player.createConnectionRequest(target.get()).fireAndForget();return;}player.getCurrentServer().ifPresent(c->player.sendMessage(messages.get("server-current","server",c.getServerInfo().getName())));Component line=messages.get("server-available-prefix");boolean first=true;for(RegisteredServer server:proxy.getAllServers()){if(!first)line=line.append(messages.get("server-separator"));first=false;String name=server.getServerInfo().getName();int count=realOn(name)+snapshot.byServer().getOrDefault(name,List.of()).size();Component entry=messages.get("server-entry","server",name,"count",count).hoverEvent(HoverEvent.showText(messages.get("server-hover","server",name,"count",count))).clickEvent(ClickEvent.runCommand("/server "+name));line=line.append(entry);}player.sendMessage(line);}public List<String> suggest(Invocation i){String prefix=i.arguments().length==0?"":i.arguments()[0].toLowerCase(Locale.ROOT);return proxy.getAllServers().stream().map(s->s.getServerInfo().getName()).filter(n->n.toLowerCase(Locale.ROOT).startsWith(prefix)).toList();}}
 private final class GlistCommand implements SimpleCommand {public void execute(Invocation i){LinkedHashSet<String> servers=new LinkedHashSet<>();settings.crowd().servers().forEach(s->servers.add(s.name()));proxy.getAllServers().forEach(s->servers.add(s.getServerInfo().getName()));for(String server:servers){List<String> players=playersOn(server);String shown=players.isEmpty()?net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer.plainText().serialize(messages.get("glist-empty-players")):String.join(", ",players);i.source().sendMessage(messages.get("glist-server-line","server",server,"count",players.size(),"players",shown));}i.source().sendMessage(messages.get("glist-total","count",total()));}public boolean hasPermission(Invocation i){return true;}}
 private final class FindCommand implements SimpleCommand {public void execute(Invocation i){if(i.arguments().length==0){i.source().sendMessage(messages.get("find-usage"));return;}String query=i.arguments()[0];Optional<Player> real=findReal(query);if(real.isPresent()){String server=real.get().getCurrentServer().map(c->c.getServerInfo().getName()).orElse("unknown");i.source().sendMessage(messages.get("find-online","player",real.get().getUsername(),"server",server));return;}findFake(query).ifPresentOrElse(location->i.source().sendMessage(messages.get("find-online","player",location.name(),"server",location.server())),()->nameResolver.correctCase(query).thenAccept(name->i.source().sendMessage(messages.get("find-offline","player",name))));}public List<String> suggest(Invocation i){return playerSuggestions(i);}public boolean hasPermission(Invocation i){return true;}}
 private final class PingCommand implements SimpleCommand {public void execute(Invocation i){if(i.arguments().length==0){if(i.source() instanceof Player player)i.source().sendMessage(messages.get("ping-self","ping",player.getPing()));else i.source().sendMessage(messages.get("players-only"));return;}String query=i.arguments()[0];Optional<Player> real=findReal(query);if(real.isPresent()){i.source().sendMessage(messages.get("ping-other","player",real.get().getUsername(),"ping",real.get().getPing()));return;}findFake(query).ifPresentOrElse(location->i.source().sendMessage(messages.get("ping-other","player",location.name(),"ping",fakePing(location.name()))),()->nameResolver.correctCase(query).thenAccept(name->i.source().sendMessage(messages.get("ping-offline","player",name))));}public List<String> suggest(Invocation i){return playerSuggestions(i);}public boolean hasPermission(Invocation i){return true;}}
 private final class AdminCommand implements SimpleCommand {public void execute(Invocation i){if(i.arguments().length>0&&i.arguments()[0].equalsIgnoreCase("reload")){try{reload();i.source().sendMessage(messages.get("reload-success"));}catch(Exception e){i.source().sendMessage(messages.get("reload-failed","error",e.getMessage()));}}else i.source().sendMessage(messages.get("status","virtual",snapshot.fakeCount(),"total",total()));}public boolean hasPermission(Invocation i){return i.source().hasPermission("crediblecrowd.admin");}}
 private List<String> combinedNames(){ArrayList<String>x=new ArrayList<>();if(settings.addToReal())proxy.getAllPlayers().forEach(p->x.add(p.getUsername()));x.addAll(snapshot.fakeNames());return x;}
 private int realOn(String server){return proxy.getServer(server).map(s->s.getPlayersConnected().size()).orElse(0);}
 private List<String> playersOn(String server){ArrayList<String> result=new ArrayList<>();proxy.getServer(server).ifPresent(s->s.getPlayersConnected().forEach(p->result.add(p.getUsername())));result.addAll(snapshot.byServer().getOrDefault(server,List.of()));return result;}
 private Optional<Player> findReal(String name){return proxy.getAllPlayers().stream().filter(p->p.getUsername().equalsIgnoreCase(name)).findFirst();}
 private Optional<FakeLocation> findFake(String name){for(var entry:snapshot.byServer().entrySet())for(String fake:entry.getValue())if(fake.equalsIgnoreCase(name))return Optional.of(new FakeLocation(fake,entry.getKey()));return Optional.empty();}
 private int fakePing(String name){int min=settings.fakePingMin(),max=settings.fakePingMax();return min+Math.floorMod(Objects.hash(name.toLowerCase(Locale.ROOT),settings.crowd().seed()),max-min+1);}
 private List<String> playerSuggestions(SimpleCommand.Invocation i){String prefix=i.arguments().length==0?"":i.arguments()[0].toLowerCase(Locale.ROOT);ArrayList<String> all=new ArrayList<>();proxy.getAllPlayers().forEach(p->all.add(p.getUsername()));all.addAll(snapshot.fakeNames());return all.stream().filter(n->n.toLowerCase(Locale.ROOT).startsWith(prefix)).limit(100).toList();}
 private record FakeLocation(String name,String server){}
}
