package ro.nectariepopa.crediblecrowd.velocity;

import com.google.inject.Inject; import com.velocitypowered.api.command.*; import com.velocitypowered.api.event.Subscribe; import com.velocitypowered.api.event.connection.LoginEvent; import com.velocitypowered.api.event.proxy.*; import com.velocitypowered.api.plugin.Plugin; import com.velocitypowered.api.plugin.annotation.DataDirectory; import com.velocitypowered.api.proxy.*; import com.velocitypowered.api.proxy.messages.MinecraftChannelIdentifier; import com.velocitypowered.api.proxy.server.ServerPing; import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.*; import java.util.*; import java.util.concurrent.TimeUnit; import net.kyori.adventure.text.Component; import net.kyori.adventure.text.format.NamedTextColor; import org.slf4j.Logger; import ro.nectariepopa.crediblecrowd.core.*;

@Plugin(id="crediblecrowd",name="CredibleCrowd",version="1.2.0",description="Consistent configurable virtual population for Velocity",authors={"nectariepopa20"},url="https://github.com/nectariepopa20/CredibleCrowd")
public final class CredibleCrowdVelocity {
 private static final MinecraftChannelIdentifier SYNC=MinecraftChannelIdentifier.create("crediblecrowd","sync"); private final ProxyServer proxy; private final Logger log; private final Path dir; private volatile VelocitySettings settings; private volatile CrowdSimulator simulator; private volatile List<String> names=List.of(); private volatile CrowdSnapshot snapshot=new CrowdSnapshot(Instant.EPOCH,0,List.of(),Map.of()); private volatile int lastBroadcastTotal=-1; private volatile long lastAdvanceEpoch;
 @Inject public CredibleCrowdVelocity(ProxyServer proxy,Logger log,@DataDirectory Path dir){this.proxy=proxy;this.log=log;this.dir=dir;}
 @Subscribe public void onStart(ProxyInitializeEvent event){try{copyDefault("config.yml");copyDefault("names.txt");reload();}catch(Exception e){throw new IllegalStateException("Cannot load CredibleCrowd",e);}proxy.getChannelRegistrar().register(SYNC); CommandMeta meta=proxy.getCommandManager().metaBuilder("glist").aliases("ccplayers").plugin(this).build();proxy.getCommandManager().register(meta,new GlistCommand()); proxy.getCommandManager().register(proxy.getCommandManager().metaBuilder("crediblecrowd").aliases("ccrowd").plugin(this).build(),new AdminCommand()); proxy.getScheduler().buildTask(this,this::scheduledRefresh).repeat(1,TimeUnit.SECONDS).schedule();refresh();log.info("CredibleCrowd enabled with {} candidate names",names.size());}
 private void scheduledRefresh(){long now=Instant.now().getEpochSecond();if(now-lastAdvanceEpoch>=settings.crowd().activityTickSeconds())refresh();}
 private synchronized void refresh(){Instant now=Instant.now();lastAdvanceEpoch=now.getEpochSecond();Set<String> real=new HashSet<>();proxy.getAllPlayers().forEach(p->real.add(p.getUsername()));CrowdSnapshot previous=snapshot;snapshot=simulator.advance(now,names,real);int displayed=total();if(!snapshot.fakeNames().equals(previous.fakeNames())||!snapshot.byServer().equals(previous.byServer())||displayed!=lastBroadcastTotal){lastBroadcastTotal=displayed;broadcast();}}
 private void broadcast(){for(var server:proxy.getAllServers()){List<String> fake=snapshot.byServer().getOrDefault(server.getServerInfo().getName(),List.of());try(var bytes=new ByteArrayOutputStream();var out=new DataOutputStream(bytes)){out.writeInt(2);out.writeInt(total());out.writeInt(fake.size());for(String name:fake)out.writeUTF(name);server.sendPluginMessage(SYNC,bytes.toByteArray());}catch(IOException e){log.warn("Could not encode sync payload",e);}}}
 private void reload() throws IOException {settings=SettingsLoader.load(dir.resolve("config.yml"));try(var lines=Files.lines(dir.resolve("names.txt"),StandardCharsets.UTF_8)){names=lines.map(String::trim).filter(s->!s.isBlank()&&!s.startsWith("#")).toList();}simulator=new CrowdSimulator(settings.crowd());lastBroadcastTotal=-1;refresh();}
 private void copyDefault(String name)throws IOException{Files.createDirectories(dir);Path target=dir.resolve(name);if(Files.notExists(target))try(InputStream in=getClass().getClassLoader().getResourceAsStream(name)){if(in==null)throw new FileNotFoundException(name);Files.copy(in,target);}}
 @Subscribe public void onPing(ProxyPingEvent event){ServerPing original=event.getPing();int real=proxy.getPlayerCount(), shown=settings.addToReal()?real+snapshot.fakeCount():snapshot.fakeCount();event.setPing(original.asBuilder().onlinePlayers(shown).maximumPlayers(Math.max(settings.maximumPlayers(),shown)).build());}
 @Subscribe public void onLogin(LoginEvent event){if(settings.reserveNames()&&snapshot.fakeNames().stream().anyMatch(n->n.equalsIgnoreCase(event.getPlayer().getUsername())))event.setResult(LoginEvent.ComponentResult.denied(Component.text(settings.deniedMessage())));}
 private int total(){return settings.addToReal()?proxy.getPlayerCount()+snapshot.fakeCount():snapshot.fakeCount();}
 private final class GlistCommand implements SimpleCommand {public void execute(Invocation i){i.source().sendMessage(Component.text("Players online ("+total()+"): ",NamedTextColor.GOLD).append(Component.text(String.join(", ",combinedNames()),NamedTextColor.WHITE)));for(var e:snapshot.byServer().entrySet())i.source().sendMessage(Component.text("["+e.getKey()+"] ("+(realOn(e.getKey())+e.getValue().size())+"): ",NamedTextColor.YELLOW).append(Component.text(String.join(", ",e.getValue()),NamedTextColor.GRAY)));}public boolean hasPermission(Invocation i){return i.source().hasPermission("crediblecrowd.glist");}}
 private final class AdminCommand implements SimpleCommand {public void execute(Invocation i){if(i.arguments().length>0&&i.arguments()[0].equalsIgnoreCase("reload")){try{reload();i.source().sendMessage(Component.text("CredibleCrowd reloaded.",NamedTextColor.GREEN));}catch(Exception e){i.source().sendMessage(Component.text("Reload failed: "+e.getMessage(),NamedTextColor.RED));}}else i.source().sendMessage(Component.text("Virtual: "+snapshot.fakeCount()+", displayed total: "+total(),NamedTextColor.AQUA));}public boolean hasPermission(Invocation i){return i.source().hasPermission("crediblecrowd.admin");}}
 private List<String> combinedNames(){ArrayList<String>x=new ArrayList<>();if(settings.addToReal())proxy.getAllPlayers().forEach(p->x.add(p.getUsername()));x.addAll(snapshot.fakeNames());return x;}
 private int realOn(String server){return proxy.getServer(server).map(s->s.getPlayersConnected().size()).orElse(0);}
}
