package ro.nectariepopa.crediblecrowd.paper;

import java.io.*; import java.util.*; import java.util.concurrent.atomic.*; import me.clip.placeholderapi.PlaceholderAPIPlugin; import me.clip.placeholderapi.expansion.PlaceholderExpansion; import org.bukkit.Bukkit; import org.bukkit.command.*; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.player.*; import org.bukkit.plugin.java.JavaPlugin; import org.bukkit.plugin.messaging.PluginMessageListener;

public final class CredibleCrowdPaper extends JavaPlugin implements PluginMessageListener,Listener,CommandExecutor {
 private static final String CHANNEL="crediblecrowd:sync"; private final AtomicReference<List<String>> fakeNames=new AtomicReference<>(List.of()); private final AtomicReference<List<VirtualPlayer>> virtualPlayers=new AtomicReference<>(List.of()); private final AtomicReference<Map<String,Integer>> serverTotals=new AtomicReference<>(Map.of()); private final AtomicInteger networkTotal=new AtomicInteger(); private volatile String localServerName=""; private volatile boolean synchronizedFromVelocity; private volatile UUID syncSession; private volatile long syncRevision; private FakeTabList tabList; private BungeeExpansion expansion; private CcExpansion ccExpansion; private VelocityExpansion velocityExpansion; private PlaceholderExpansion replacedExpansion; private PlaceholderExpansion replacedVelocityExpansion;
 @Override public void onEnable(){saveDefaultConfig();getServer().getMessenger().registerIncomingPluginChannel(this,CHANNEL,this);getServer().getPluginManager().registerEvents(this,this);Objects.requireNonNull(getCommand("ccplayers")).setExecutor(this);setupPlaceholderApi();setupTabList();getLogger().info("Paper bridge ready; waiting for Velocity sync.");}
 @Override public void onDisable(){if(tabList!=null)tabList.clear(fakeNames.get());if(expansion!=null)expansion.unregister();if(ccExpansion!=null)ccExpansion.unregister();if(velocityExpansion!=null)velocityExpansion.unregister();if(replacedExpansion!=null)replacedExpansion.register();if(replacedVelocityExpansion!=null)replacedVelocityExpansion.register();getServer().getMessenger().unregisterIncomingPluginChannel(this,CHANNEL,this);}
 private void setupPlaceholderApi(){if(Bukkit.getPluginManager().isPluginEnabled("PlaceholderAPI")){var manager=PlaceholderAPIPlugin.getInstance().getLocalExpansionManager();replacedExpansion=manager.getExpansion("bungee");if(replacedExpansion!=null){manager.unregister(replacedExpansion);getLogger().info("Temporarily replaced the existing PlaceholderAPI bungee expansion.");}replacedVelocityExpansion=manager.getExpansion("velocity");if(replacedVelocityExpansion!=null){manager.unregister(replacedVelocityExpansion);getLogger().info("Temporarily replaced the existing PlaceholderAPI velocity expansion.");}expansion=new BungeeExpansion(this);ccExpansion=new CcExpansion(this);velocityExpansion=new VelocityExpansion(this);if(!expansion.register())getLogger().warning("Could not register the compatibility bungee expansion.");if(!ccExpansion.register())getLogger().warning("Could not register the PlaceholderAPI cc expansion.");if(!velocityExpansion.register())getLogger().warning("Could not register the native PlaceholderAPI velocity expansion.");else getLogger().info("Registered native Velocity placeholders: %velocity_total%, %velocity_server%, and %velocity_<server>%.");}else getLogger().warning("PlaceholderAPI not found; CredibleCrowd placeholders are disabled.");}
 private void setupTabList(){if(!getConfig().getBoolean("fake-tablist",true))return;if(Bukkit.getPluginManager().isPluginEnabled("ProtocolLib"))tabList=new FakeTabList(getConfig().getInt("fake-tablist-latency",45));else getLogger().warning("ProtocolLib not found; virtual tab-list entries are disabled.");}
 @Override public void onPluginMessageReceived(String channel,Player player,byte[] message){if(!CHANNEL.equals(channel))return;try(var in=new DataInputStream(new ByteArrayInputStream(message))){int version=in.readInt();int total=version>=2?in.readInt():Bukkit.getOnlinePlayers().size();if(version<1||version>4||total<0)throw new IOException("Unsupported payload");Map<String,Integer> totals=Map.of();String decodedLocalName=localServerName;if(version>=3){decodedLocalName=in.readUTF();int servers=in.readInt();if(servers<0||servers>10000)throw new IOException("Invalid server count");LinkedHashMap<String,Integer> decoded=new LinkedHashMap<>();for(int i=0;i<servers;i++){String name=in.readUTF();int value=in.readInt();if(value<0)throw new IOException("Invalid server total");decoded.put(name,value);}totals=Map.copyOf(decoded);}int count=in.readInt();if(count<0||count>100000)throw new IOException("Invalid count");ArrayList<String> names=new ArrayList<>(count);for(int i=0;i<count;i++)names.add(in.readUTF());UUID decodedSession=syncSession;long revision=syncRevision+1;List<VirtualPlayer> identities=names.stream().map(name->new VirtualPlayer(stableLegacyId(name),name)).toList();List<VirtualPlayer> joined=List.of(),departed=List.of();if(version>=4){decodedSession=new UUID(in.readLong(),in.readLong());revision=in.readLong();identities=readIdentities(in,count,"identity");joined=readIdentities(in,100000,"joined");departed=readIdentities(in,100000,"departed");if(identities.size()!=names.size())throw new IOException("Identity/name count mismatch");for(int i=0;i<names.size();i++)if(!names.get(i).equals(identities.get(i).name()))throw new IOException("Identity/name order mismatch");if(decodedSession.equals(syncSession)&&revision<=syncRevision)return;}else{Map<UUID,VirtualPlayer> oldById=new LinkedHashMap<>();virtualPlayers.get().forEach(value->oldById.put(value.id(),value));Set<UUID> nextIds=identities.stream().map(VirtualPlayer::id).collect(java.util.stream.Collectors.toSet());joined=identities.stream().filter(value->!oldById.containsKey(value.id())).toList();departed=oldById.values().stream().filter(value->!nextIds.contains(value.id())).toList();}List<String> old=fakeNames.getAndSet(List.copyOf(names));virtualPlayers.set(List.copyOf(identities));serverTotals.set(totals);networkTotal.set(total);localServerName=decodedLocalName;syncSession=decodedSession;syncRevision=revision;if(!synchronizedFromVelocity){synchronizedFromVelocity=true;getLogger().info("Received Velocity population snapshot for '"+localServerName+"' with "+totals.size()+" server totals.");}if(tabList!=null)tabList.replace(old,names);Bukkit.getPluginManager().callEvent(new VirtualPlayersUpdatedEvent(revision,identities,joined,departed));}catch(IOException e){getLogger().warning("Rejected invalid Velocity sync payload: "+e.getMessage());}}
 private static List<VirtualPlayer> readIdentities(DataInputStream in,int maximum,String label)throws IOException{int count=in.readInt();if(count<0||count>maximum)throw new IOException("Invalid "+label+" count");ArrayList<VirtualPlayer> result=new ArrayList<>(count);HashSet<UUID> seen=new HashSet<>();for(int i=0;i<count;i++){UUID id=new UUID(in.readLong(),in.readLong());String name=in.readUTF();if(!seen.add(id))throw new IOException("Duplicate "+label+" identity");result.add(new VirtualPlayer(id,name));}return List.copyOf(result);}
 private static UUID stableLegacyId(String name){return UUID.nameUUIDFromBytes(("crediblecrowd:virtual-player:"+name.toLowerCase(Locale.ROOT)).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 @EventHandler public void onJoin(PlayerJoinEvent event){if(tabList!=null)Bukkit.getScheduler().runTaskLater(this,()->tabList.show(event.getPlayer(),fakeNames.get()),1L);}
 @EventHandler(priority=EventPriority.HIGHEST) public void onPlayerCommand(PlayerCommandPreprocessEvent event){if(getConfig().getBoolean("intercept-list-command",true)&&isList(event.getMessage())){event.setCancelled(true);event.getPlayer().sendMessage(render());}}
 @EventHandler(priority=EventPriority.HIGHEST) public void onConsoleCommand(org.bukkit.event.server.ServerCommandEvent event){if(getConfig().getBoolean("intercept-list-command",true)&&isList(event.getCommand())){event.setCancelled(true);event.getSender().sendMessage(render());}}
 private boolean isList(String command){String c=command.startsWith("/")?command.substring(1):command;c=c.trim().toLowerCase(Locale.ROOT);return c.equals("list")||c.equals("minecraft:list");}
 private String render(){List<String> all=new ArrayList<>();Bukkit.getOnlinePlayers().forEach(p->all.add(p.getName()));all.addAll(fakeNames.get());return getConfig().getString("list-format","There are {count} of a max of {max} players online: {players}").replace("{count}",String.valueOf(all.size())).replace("{max}",String.valueOf(Bukkit.getMaxPlayers())).replace("{players}",String.join(", ",all));}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){sender.sendMessage(render());return true;}
 public List<String> getVirtualPlayers(){return fakeNames.get();}
 public List<VirtualPlayer> getVirtualPlayerIdentities(){return virtualPlayers.get();}
 public long getSyncRevision(){return syncRevision;}
 public String getLocalServerName(){return localServerName;}
 public int getNetworkTotal(){return networkTotal.get();}
 public int getLocalTotal(){return Bukkit.getOnlinePlayers().size()+fakeNames.get().size();}
 public String resolveNetworkPlaceholder(String parameter,boolean includeFake){String key=parameter.toLowerCase(Locale.ROOT);if(key.equals("total"))return String.valueOf(getNetworkTotal());if(key.equals("server"))return String.valueOf(getLocalTotal());if(key.equals("server_name"))return localServerName;if(includeFake&&key.equals("fake"))return String.valueOf(fakeNames.get().size());for(var entry:serverTotals.get().entrySet())if(entry.getKey().equalsIgnoreCase(parameter))return String.valueOf(entry.getValue());return null;}
}
