package ro.nectariepopa.crediblecrowd.paper;

import java.io.*; import java.util.*; import java.util.concurrent.atomic.*; import me.clip.placeholderapi.PlaceholderAPIPlugin; import me.clip.placeholderapi.expansion.PlaceholderExpansion; import org.bukkit.Bukkit; import org.bukkit.command.*; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.player.*; import org.bukkit.plugin.java.JavaPlugin; import org.bukkit.plugin.messaging.PluginMessageListener;

public final class CredibleCrowdPaper extends JavaPlugin implements PluginMessageListener,Listener,CommandExecutor {
 private static final String CHANNEL="crediblecrowd:sync"; private final AtomicReference<List<String>> fakeNames=new AtomicReference<>(List.of()); private final AtomicInteger networkTotal=new AtomicInteger(); private FakeTabList tabList; private BungeeExpansion expansion; private CcExpansion ccExpansion; private PlaceholderExpansion replacedExpansion;
 @Override public void onEnable(){saveDefaultConfig();getServer().getMessenger().registerIncomingPluginChannel(this,CHANNEL,this);getServer().getPluginManager().registerEvents(this,this);Objects.requireNonNull(getCommand("ccplayers")).setExecutor(this);setupPlaceholderApi();setupTabList();getLogger().info("Paper bridge ready; waiting for Velocity sync.");}
 @Override public void onDisable(){if(tabList!=null)tabList.clear(fakeNames.get());if(expansion!=null)expansion.unregister();if(ccExpansion!=null)ccExpansion.unregister();if(replacedExpansion!=null)replacedExpansion.register();getServer().getMessenger().unregisterIncomingPluginChannel(this,CHANNEL,this);}
 private void setupPlaceholderApi(){if(Bukkit.getPluginManager().isPluginEnabled("PlaceholderAPI")){var manager=PlaceholderAPIPlugin.getInstance().getLocalExpansionManager();replacedExpansion=manager.getExpansion("bungee");if(replacedExpansion!=null){manager.unregister(replacedExpansion);getLogger().info("Temporarily replaced the existing PlaceholderAPI bungee expansion.");}expansion=new BungeeExpansion(this);ccExpansion=new CcExpansion(this);if(!expansion.register())getLogger().warning("Could not register the PlaceholderAPI bungee expansion.");if(!ccExpansion.register())getLogger().warning("Could not register the PlaceholderAPI cc expansion.");}else getLogger().warning("PlaceholderAPI not found; CredibleCrowd placeholders are disabled.");}
 private void setupTabList(){if(!getConfig().getBoolean("fake-tablist",true))return;if(Bukkit.getPluginManager().isPluginEnabled("ProtocolLib"))tabList=new FakeTabList(getConfig().getInt("fake-tablist-latency",45));else getLogger().warning("ProtocolLib not found; virtual tab-list entries are disabled.");}
 @Override public void onPluginMessageReceived(String channel,Player player,byte[] message){if(!CHANNEL.equals(channel))return;try(var in=new DataInputStream(new ByteArrayInputStream(message))){int version=in.readInt();int total=version>=2?in.readInt():Bukkit.getOnlinePlayers().size();if(version<1||version>2||total<0)throw new IOException("Unsupported payload");int count=in.readInt();if(count<0||count>100000)throw new IOException("Invalid count");ArrayList<String> names=new ArrayList<>(count);for(int i=0;i<count;i++)names.add(in.readUTF());List<String> old=fakeNames.getAndSet(List.copyOf(names));networkTotal.set(total);if(tabList!=null)tabList.replace(old,names);}catch(IOException e){getLogger().warning("Rejected invalid Velocity sync payload: "+e.getMessage());}}
 @EventHandler public void onJoin(PlayerJoinEvent event){if(tabList!=null)Bukkit.getScheduler().runTaskLater(this,()->tabList.show(event.getPlayer(),fakeNames.get()),1L);}
 @EventHandler(priority=EventPriority.HIGHEST) public void onPlayerCommand(PlayerCommandPreprocessEvent event){if(getConfig().getBoolean("intercept-list-command",true)&&isList(event.getMessage())){event.setCancelled(true);event.getPlayer().sendMessage(render());}}
 @EventHandler(priority=EventPriority.HIGHEST) public void onConsoleCommand(org.bukkit.event.server.ServerCommandEvent event){if(getConfig().getBoolean("intercept-list-command",true)&&isList(event.getCommand())){event.setCancelled(true);event.getSender().sendMessage(render());}}
 private boolean isList(String command){String c=command.startsWith("/")?command.substring(1):command;c=c.trim().toLowerCase(Locale.ROOT);return c.equals("list")||c.equals("minecraft:list");}
 private String render(){List<String> all=new ArrayList<>();Bukkit.getOnlinePlayers().forEach(p->all.add(p.getName()));all.addAll(fakeNames.get());return getConfig().getString("list-format","There are {count} of a max of {max} players online: {players}").replace("{count}",String.valueOf(all.size())).replace("{max}",String.valueOf(Bukkit.getMaxPlayers())).replace("{players}",String.join(", ",all));}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){sender.sendMessage(render());return true;}
 public List<String> getVirtualPlayers(){return fakeNames.get();}
 public int getNetworkTotal(){return networkTotal.get();}
 public int getLocalTotal(){return Bukkit.getOnlinePlayers().size()+fakeNames.get().size();}
}
